"""Constants for the Napoleon Grill integration."""

DOMAIN = "napoleon_grill"
MANUFACTURER = "Napoleon"

# Ayla Networks API
AYLA_USER_FIELD_URL = "https://user-field.aylanetworks.com"
AYLA_ADS_URL = "https://ads-field.aylanetworks.com"

# Config flow keys
CONF_APP_ID = "app_id"
CONF_APP_SECRET = "app_secret"

# Update interval in seconds
SCAN_INTERVAL_SECONDS = 30

# Property names from Ayla API
PROP_GRILL_MODE = "BSMODE"
PROP_BURNER_LEVEL = "BT_LVL"
PROP_BRIGHTNESS_LEVEL = "BRT_LVL"
PROP_PROBE_STATUS = "PRB_STAT"
PROP_PROBE_ONE_TEMP = "PRB_TMP_ONE"
PROP_PROBE_TWO_TEMP = "PRB_TMP_TWO"
PROP_PROBE_THREE_TEMP = "PRB_TMP_THREE"
PROP_PROBE_FOUR_TEMP = "PRB_TMP_FOUR"
PROP_PROBE_ONE_NAME = "PRB_ONE_NME"
PROP_PROBE_TWO_NAME = "PRB_TWO_NME"
PROP_PROBE_THREE_NAME = "PRB_THREE_NME"
PROP_PROBE_FOUR_NAME = "PRB_FOUR_NME"
PROP_TARGET_TEMP_ONE = "TRGT_TMP_ONE"
PROP_TARGET_TEMP_TWO = "TRGT_TMP_TWO"
PROP_TARGET_TEMP_THREE = "TRGT_TMP_THREE"
PROP_TARGET_TEMP_FOUR = "TRGT_TMP_FOUR"
PROP_TEMP_UNIT = "TUNIT"
PROP_TANK_WEIGHT = "TNK_WT"
PROP_RSSI = "RSSI"
PROP_LCD_OFF = "LCD_OFF"
PROP_DEVICE_NAME = "DEVC_NME"
PROP_VERSION = "version"

# Brightness levels
BRIGHTNESS_LOW = 1
BRIGHTNESS_MEDIUM = 3
BRIGHTNESS_HIGH = 5
BRIGHTNESS_OPTIONS = {
    "Low": BRIGHTNESS_LOW,
    "Medium": BRIGHTNESS_MEDIUM,
    "High": BRIGHTNESS_HIGH,
}

# Target temperature sentinel value (means "not set")
TRGT_TMP_NOT_SET = 4095

# Writable properties
PROP_TARGET_TEMP_ONE = "TRGT_TMP_ONE"
PROP_TARGET_TEMP_TWO = "TRGT_TMP_TWO"
PROP_TARGET_TEMP_THREE = "TRGT_TMP_THREE"
PROP_TARGET_TEMP_FOUR = "TRGT_TMP_FOUR"
PROP_COOK_PRESET_ONE = "CKNME_PRB_ONE"
PROP_COOK_PRESET_TWO = "CKNME_PRB_TWO"
PROP_COOK_PRESET_THREE = "CKNME_PRB_THREE"
PROP_COOK_PRESET_FOUR = "CKNME_PRB_FOUR"